// <auto-generated />
using System;
using Apartment.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Apartment.Infrastructure.Migrations.QueryDb
{
    [DbContext(typeof(QueryDbContext))]
    [Migration("20240802151120_InitialQueryDb")]
    partial class InitialQueryDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Apartment.Domain.QueryEntities.BlockQuery", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BlockId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteId")
                        .HasColumnType("text");

                    b.Property<string>("SiteQueryId")
                        .HasColumnType("text");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SiteQueryId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("Apartment.Domain.QueryEntities.SiteQuery", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ManagerId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("Apartment.Domain.QueryEntities.UnitQuery", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BlockId")
                        .HasColumnType("text");

                    b.Property<string>("BlockQueryId")
                        .HasColumnType("text");

                    b.Property<bool>("HasCar")
                        .HasColumnType("boolean");

                    b.Property<string>("ResidentId")
                        .HasColumnType("text");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UnitNo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlockQueryId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Apartment.Domain.QueryEntities.VisitQuery", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasCar")
                        .HasColumnType("boolean");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("text");

                    b.Property<string>("UnitId")
                        .HasColumnType("text");

                    b.Property<string>("VisitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Apartment.Domain.QueryEntities.BlockQuery", b =>
                {
                    b.HasOne("Apartment.Domain.QueryEntities.SiteQuery", null)
                        .WithMany("Blocks")
                        .HasForeignKey("SiteQueryId");
                });

            modelBuilder.Entity("Apartment.Domain.QueryEntities.UnitQuery", b =>
                {
                    b.HasOne("Apartment.Domain.QueryEntities.BlockQuery", null)
                        .WithMany("Units")
                        .HasForeignKey("BlockQueryId");
                });

            modelBuilder.Entity("Apartment.Domain.QueryEntities.BlockQuery", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("Apartment.Domain.QueryEntities.SiteQuery", b =>
                {
                    b.Navigation("Blocks");
                });
#pragma warning restore 612, 618
        }
    }
}
